output:				rocket_dodge.o
	g++ rocket_dodge.o -o rocketdodge -lGL -lGLU -lglut

rocket_dodge.o: rocket_dodge.cpp
	g++ -Wall -g -c rocket_dodge.cpp 

clean: 				
	rm rocket_dodge.o rocketdodge



# g++ -Wall -g -c rocket_dodge.cpp 
# g++ rocket_dodge.o -o rocketdodge -lGL -lGLU -lglut

