output:				spaceshooter.o
	g++ spaceshooter.o -o spaceshooter -lGL -lGLU -lglut

spaceshooter.o: spaceshooter.cpp
	g++ -Wall -g -c spaceshooter.cpp 

clean: 				
	rm spaceshooter.o spaceshooter



# g++ -Wall -g -c spaceshooter_test.cpp
# g++ -Wall -g spaceshooter_test.o -o spaceshooter.out -lGL -lGLU -lglut
